### ISSUE TITLE
Provide isinstance and issubclass equivalents

### ISSUE THREAD

**Issue by smarie** [ilevkivskyi/typing_inspect#9] opened 2017-09-12 15:20 UTC
In one of my [projects](https://github.com/smarie/python-parsyfiles) I had to implement this function, I guess it could be useful to share in `typing_inspect`, and also to provide the equivalent for subclass tests, what do you think ? (I did not find any equivalent in `typing` nor in `typing_inspect`)

```python
from typing import Any, Type
from typing_inspect import is_union_type, get_args, get_origin

def robust_isinstance(inst: Any, typ: Type):
    """
    Similar to isinstance, but if 'typ' is a parametrized generic Type, it is first transformed into 
    its base generic class so that the instance check works. It is also robust to Union and Any.

    :param inst: the instance to check against the type
    :param typ: the type
    :return:
    """
    if typ is Any:
        return True
    elif is_union_type(typ):
        typs = get_args(typ)
        if len(typs) > 0:
            return any(robust_isinstance(inst, t) for t in typs)
        else:
            return False
    else:
        return isinstance(inst, get_base_generic_type(typ))
```

Note that we could also provide a boolean parameter to enable finer-grain subclass/isinstance checks for example for parametrized generic types. For example to make this return False: `robust_isinstance([1], List[str])`

**Comment by ilevkivskyi** [comment] 2017-09-12 20:08
I haven't heard many requests for this yet, but maybe this can be considered at some point. Currently the focus is on introspection rather than on validation (also I was busy with some other projects, sorry).

**Comment by Stewori** [comment] 2017-09-12 22:53
I suppose this is partly a duplicate of https://github.com/ilevkivskyi/typing_inspect/issues/2.
[pytypes](https://github.com/Stewori/pytypes) offers the utility functions [is_of_type](https://github.com/Stewori/pytypes#is_of_typeobj-cls) and [is_subtype](https://github.com/Stewori/pytypes#is_subtypesubtype-supertype).
These should be able to do the requested thing, at least they are supposed to.

**Comment by ilevkivskyi** [comment] 2017-09-13 07:56
> pytypes offers the utility functions is_of_type and is_subtype.

Ah, thanks, I forgot about this. @smarie I think it would be much better to just use ``pytypes`` instead of putting some more limited version in ``typing_inspect`` (anyway there is a little chance this functionality will be eventually added to ``typing``).

**Closed by ilevkivskyi** 2017-09-13 07:56 UTC
Labels: enhancement

**Comment by smarie** [comment] 2017-09-13 08:11
Great, thanks ! Although I am a bit sad to discover yet another typechecking library after several attempts of searching, finding new ones, testing, rejecting. My latest choice of such tools was [`enforce`](https://github.com/RussBaz/enforce) which does the job nicely - therefore I suggest its usage in my class code generation tool [`autoclass`](https://smarie.github.io/python-autoclass/). I will probably also include [`pytypes`](https://github.com/Stewori/pytypes) then.

However I don't agree that such libraries should both provide runtime typechecking annotations **and** an internal API for manual type checking. These can be two different concerns: the first one has a much broader audience, while the second one is mostly a tool for libraries developers, no?
My two cents... :)

**Comment by Stewori** [comment] 2017-09-13 13:11
> However I don't agree that such libraries should both provide runtime typechecking annotations and an internal API for manual type checking.

The thing is, typechecking annotations would internally need the API for (manual) type checking anyway. So the latter is a by-product of the former or in turn the former is a low-hanging fruit if the latter is given. That's why it makes sense to offer both feature areas within the same framework.

> My latest choice of such tools was enforce

I also saw encforce, typeguard and some more frameworks, but none of them seemed to support stub files, which I find a crucial feature as it unlocks typeshed. (Python 2.7 support is another thing, but I guess this isn't much of interest for you).
